### PR TITLE
feat: add default export

### PR DESCRIPTION
**Pull request by bluelovers**

### CODE REVIEW

**Comment by nwoltman** [comment]
I don't see why this is necessary. This module already works with ECMAScript Modules syntax:

```js
// index.js
import stringNaturalCompare from 'string-natural-compare';

console.log(stringNaturalCompare);
```

```sh
> node .\index.js
(node:9800) ExperimentalWarning: The ESM module loader is experimental.
[Function: naturalCompare]
```

**Comment by bluelovers** [comment]
this can help when use typescript but didn't enable `esModuleInterop`
can still use `import stringNaturalCompare from 'string-natural-compare';`

**Comment by nwoltman** [comment]
I see, so this is specifically for TypeScript. If TypeScript provides a way for you to import CommonJS modules, you should use it. I can't accept this change because it doesn't follow any standard format. This module is already a CommonJS module, which is a standard format that other tools should be able to work with.

Making this change here also isn't a good solution for your project. If you use another npm module, you'll need to make this same change to that module for it to conform to your project. Then you'll need to do the same for every module that you add to your project. The proper solution is to configure your project so that it works with external modules that are in a standard format.

**Comment by bluelovers** [comment]
because that option will change output code
and that will make some bug of typescript can't fix it

**Comment by nwoltman** [comment]
Would you be able to create a repo that demonstrates the problem? I don't understand what the problem is so I'd need to see some code to be able to help find a solution.

**Pull request closed without merging**
